/*
	--------------------------------------------------------------------
	Summary
	--------------------------------------------------------------------

	A small rendering experiment that constructs a minimal framebuffer 
	which stores pixels directly into RAM and then blits them to the screen
	all at once. Patterns are programmatically generated through manipulating 
	each color byte every frame in order to give the appearance of animation.

	Pattern functions are duplicated with only minor changes for each of them
	so that anyone interested in taking a look at the code could quickly see
	how each pattern was generated without diving into complex macro setups
	or other solutions for the sole purpose preventing code duplication.

	Tested on Windows 11 64bit machines but this should also work on a 32bit
	Windows system as well.
*/

#ifndef UNICODE
#define UNICODE
#endif

#ifdef _WIN32
#define WIN32_LEAD_AND_MEAN
#define NOMINMAX
#include <windows.h>
#include <stdint.h>

#define DEFAULT_WINDOW_WIDTH  1280
#define DEFAULT_WINDOW_HEIGHT 720

static int ProgramRunning = 1;

/* Memory or pixels should be formatted as 3 bytes for BGR colors and one extra
byte left over for an even 4 byte alignment. */
typedef struct ColorBGR
{
	uint8_t Blue;
	uint8_t Green;
	uint8_t Red;
	uint8_t Padding; // Should be skipped over or set to 0
} ColorBGR;

typedef struct ApplicationWindow
{
	HWND Handle;

	// Tracking these so that the framebuffer can properly scale with the client area
	RECT ClientRect;
	LONG ClientWidth;
	LONG ClientHeight;

	uint8_t Fullscreen;
} ApplicationWindow;

typedef struct BitmapFramebuffer
{
	BITMAPINFO Info;       // Format information
	ColorBGR* PixelMemory; // Pointer to the start of a contiguous block of pixels
	size_t Size;           // The total size in bytes of the framebuffer
} BitmapFramebuffer;

// Represents each pattern preset that can be swapped at runtime
typedef enum BGRPatternTypes
{
	MONOCHROME,
	DREAM_SEQUENCE,
	STAINED_GLASS,
	PANELS,
	CHAOS
} BGRPatternTypes;

static BGRPatternTypes PatternCurrent = MONOCHROME;

static int8_t PatternHorizontalSpeed = 1;
static int8_t PatternVerticalSpeed   = 1;
static uint8_t PatternPaused         = 0;

static BitmapFramebuffer Framebuffer = {0};
static ApplicationWindow Window      = {0};

static uint8_t PatternOffsetX = 0;
static uint8_t PatternOffsetY = 0;

/* These patterns are generated by taking every single pixel that is in the fraembuffer and
manipulating them programatically through row and column loops. The framebuffer is properly
sized to fit the client area of the window and so each pattern function just has to worry 
about looping through the pixels and updating them. */

static void GenerateMonochrome()
{
	ColorBGR* pixels = Framebuffer.PixelMemory;

	for (int y = 0; y < Framebuffer.Info.bmiHeader.biHeight; y++)
	{
		for (int x = 0;  x < Framebuffer.Info.bmiHeader.biWidth; x++)
		{
			pixels->Blue  = (((x - y) | 16) + PatternOffsetX);
			pixels->Green = (((x - y) | 16) + PatternOffsetX);
			pixels->Red   = (((x - y) | 16) + PatternOffsetX);
			pixels++;
		}
	}
}

static void GenerateDreamSequence()
{
	ColorBGR* pixels = Framebuffer.PixelMemory;

	for (int y = 0; y < Framebuffer.Info.bmiHeader.biHeight; y++)
	{
		for (int x = 0; x < Framebuffer.Info.bmiHeader.biWidth; x++)
		{
			pixels->Blue  = (x - y) + PatternOffsetX;
			pixels->Green = (y + x) - PatternOffsetY;
			pixels->Red   = (x - y);
			pixels++;
		}
	}
}

static void GenerateStainedGlass()
{
	ColorBGR* pixels = Framebuffer.PixelMemory;

	for (int y = 0; y < Framebuffer.Info.bmiHeader.biHeight; y++)
	{
		for (int x = 0; x < Framebuffer.Info.bmiHeader.biWidth; x++)
		{
			pixels->Blue  = (x - y) + PatternOffsetX;
			pixels->Green = (y + x) - PatternOffsetY;
			pixels->Red   = x;
			pixels++;
		}
	}
}

static void GeneratePanels()
{
	ColorBGR* pixels = Framebuffer.PixelMemory;

	for (int y = 0; y < Framebuffer.Info.bmiHeader.biHeight; y++)
	{
		for (int x = 0; x < Framebuffer.Info.bmiHeader.biWidth; x++)
		{
			pixels->Blue  = 64      + PatternOffsetX;
			pixels->Green = (x + x) + PatternOffsetY;
			pixels->Red   = (x + x) + PatternOffsetY;
			pixels++;
		}
	}
}

static void GenerateChaos()
{
	ColorBGR* pixels = Framebuffer.PixelMemory;

	for (int y = 0; y < Framebuffer.Info.bmiHeader.biHeight; y++)
	{
		for (int x = 0; x < Framebuffer.Info.bmiHeader.biWidth; x++)
		{
			pixels->Blue  = (((x - y) | 16) * PatternOffsetY);
			pixels->Green = (y + x) ^         PatternOffsetX;
			pixels->Red   = (x ^ x) |         PatternOffsetY;
			pixels++;
		}
	}
}

/* Writes the currently selected pattern to the framebuffer and then
copies the framebuffer to the screen and stretches it if needed. At 
the end of every blit, the global horizontal and vertical offsets are 
updated in order to keep the framebuffer constantly animating. */

static void BlitPattern()
{
	if (!Framebuffer.PixelMemory)
	{
		return;
	}

	switch (PatternCurrent)
	{
		case MONOCHROME:     GenerateMonochrome();    break;
		case DREAM_SEQUENCE: GenerateDreamSequence(); break;
		case STAINED_GLASS:  GenerateStainedGlass();  break;
		case PANELS:         GeneratePanels();         break;
		case CHAOS:          GenerateChaos();         break;
	}

	HDC deviceContext = GetDC(Window.Handle);

	/* This could be modifed to have a source or destination rectangle 
	that is not the entire size of the client area or framebuffer 
	to create smaller portions of the screen that is drawn to, but 
	for this program I am opting to just fill the entire screen for 
	the best pattern appearance. */

	StretchDIBits(
		deviceContext,
		0, 0,
		Window.ClientWidth, Window.ClientHeight,
		0, 0,
		Framebuffer.Info.bmiHeader.biWidth, Framebuffer.Info.bmiHeader.biHeight,
		Framebuffer.PixelMemory,
		&Framebuffer.Info,
		DIB_RGB_COLORS, SRCCOPY
	);

	ReleaseDC(Window.Handle, deviceContext);

	if (PatternPaused)
	{
		return;
	}

	PatternOffsetX += PatternHorizontalSpeed;
	PatternOffsetY += PatternVerticalSpeed;
}

/* Changes the size of the framebuffer by allocating memory pages
exclusively for the pixels. The framebuffer can be any size and does 
not have to fit the entire client area of the window, but this 
comes with possible visual issues when trying to stretch pixels to 
fit the screen, or if trying to draw to somewhere outside of the 
client area. To prevent these issues, I decided just to have the 
program always scale with the window. */

static void ResizeFramebuffer(LONG width, LONG height)
{
	if (Framebuffer.PixelMemory)
	{
		VirtualFree(Framebuffer.PixelMemory, 0, MEM_RELEASE);
	}

	Framebuffer.Info.bmiHeader.biWidth  = width;
	Framebuffer.Info.bmiHeader.biHeight = height;

	Framebuffer.Size = (size_t)width * (size_t)height * sizeof(ColorBGR);

	Framebuffer.PixelMemory = VirtualAlloc(NULL, Framebuffer.Size, MEM_RESERVE | MEM_COMMIT, PAGE_READWRITE);

	if (!Framebuffer.PixelMemory)
	{
		Framebuffer.Size = 0;
	}
}

static LRESULT CALLBACK WindowProc(HWND windowHandle, UINT message, WPARAM wParam, LPARAM lParam)
{
	switch (message)
	{
		case WM_SIZE:
		{
			GetClientRect(windowHandle, &Window.ClientRect);

			Window.ClientWidth  = Window.ClientRect.right - Window.ClientRect.left;
			Window.ClientHeight = Window.ClientRect.bottom - Window.ClientRect.top;

			if (Window.ClientWidth <= 0 || Window.ClientHeight <= 0)
			{
				return 0;
			}

			ResizeFramebuffer(Window.ClientWidth, Window.ClientHeight);
			return 0;
		}

		/* When resizing the screen Windows will try to paint a background color into
		the new area of the window that was just exposed and so in order to have the
		pattern show immediately in this new client area space the framebuffer should
		immediately present what it has to the screen to fill up that empty space. As
		long as the framebuffer is resized prior to a new WM_PAINT call, it will be
		the appropriate width and height. */

		case WM_PAINT:
		{
			PAINTSTRUCT paint;
			HDC deviceContext = BeginPaint(windowHandle, &paint);

			BlitPattern();

			EndPaint(windowHandle, &paint);
			return 0;
		}
		case WM_DESTROY:
		{
			PostQuitMessage(0);
			return 0;
		}
		case WM_KEYDOWN:
		{
			switch (wParam)
			{
				// Set pattern.
				case '1':
				{
					PatternCurrent = MONOCHROME;
					SetWindowText(Window.Handle, L"Pattern: MONOCHROME");
					break;
				}
				case '2':
				{
					PatternCurrent = DREAM_SEQUENCE;
					SetWindowText(Window.Handle, L"Pattern: DREAM_SEQUENCE");
					break;
				}
				case '3':
				{
					PatternCurrent = STAINED_GLASS;
					SetWindowText(Window.Handle, L"Pattern: STAINED_GLASS");
					break;
				}
				case '4':
				{
					PatternCurrent = PANELS;
					SetWindowText(Window.Handle, L"Pattern: PANELS");
					break;
				}
				case '5':
				{
					PatternCurrent = CHAOS;
					SetWindowText(Window.Handle, L"Pattern: CHAOS");
					break;
				}

				// Reset pattern controls.
				case 'R':
				{
					PatternHorizontalSpeed = 1;
					PatternVerticalSpeed   = 1;
					break;
				}

				// Update animation speed.
				case VK_DOWN:  PatternVerticalSpeed--;   break;
				case VK_UP:    PatternVerticalSpeed++;   break;
				case VK_LEFT:  PatternHorizontalSpeed--; break;
				case VK_RIGHT: PatternHorizontalSpeed--; break;

				// Pause the animation
				case VK_SPACE: PatternPaused = !PatternPaused; break;

				// Fullscreen toggle.
				case VK_F11:
				{
					Window.Fullscreen = !Window.Fullscreen;

					if (Window.Fullscreen)
					{
						/* Setting the window as a popup will remove window decorations.
						This is not the correct way to handle fullscreen mode in a larger
						piece of software but for the sake of keeping this project focused
						on the renderer, it is a great workaround. */

						SetWindowLongPtr(windowHandle, GWL_STYLE, WS_VISIBLE | WS_OVERLAPPEDWINDOW);
						ShowWindow(windowHandle, SW_MAXIMIZE);
					}
					else
					{
						SetWindowLongPtr(windowHandle, GWL_STYLE, WS_VISIBLE | WS_OVERLAPPEDWINDOW);
						ShowWindow(windowHandle, SW_SHOWNORMAL);
					}

					break;
				}
			}

			return 0;
		}

		default:
		{
			return DefWindowProc(windowHandle, message, wParam, lParam);
		}
	}
}

int WINAPI wWinMain(HINSTANCE instance, HINSTANCE prevInstance, PWSTR cmdArgs, int show)
{
	WNDCLASS windowClass      = {0};
	windowClass.style         = CS_HREDRAW | CS_VREDRAW;
	windowClass.lpfnWndProc   = WindowProc;
	windowClass.hInstance     = instance;
	windowClass.lpszClassName = L"MainWindowClass";

	RegisterClass(&windowClass);

	// Setting up the default state of the framebuffer.
	// This MUST be called before the window is shown for the first time.

	Framebuffer.Info.bmiHeader.biSize = sizeof(Framebuffer.Info.bmiHeader);
	Framebuffer.Info.bmiHeader.biWidth = DEFAULT_WINDOW_WIDTH;
	Framebuffer.Info.bmiHeader.biHeight = DEFAULT_WINDOW_HEIGHT;
	Framebuffer.Info.bmiHeader.biPlanes = 1;
	Framebuffer.Info.bmiHeader.biBitCount = 32;
	Framebuffer.Info.bmiHeader.biCompression = BI_RGB;

	Window.Handle = CreateWindowEx(
		0,
		L"MainWindowClass", L"Pattern: MONOCHROME",
		WS_OVERLAPPEDWINDOW,
		CW_USEDEFAULT, CW_USEDEFAULT,
		DEFAULT_WINDOW_WIDTH, DEFAULT_WINDOW_HEIGHT,
		NULL, NULL,
		instance,
		NULL
	);

	if (Window.Handle == NULL)
	{
		return 1;
	}

	Window.Fullscreen = 0;
	ShowWindow(Window.Handle, 1);

	while (ProgramRunning == 1)
	{
		MSG message = {0};
		while (PeekMessage(&message, 0, 0, 0, PM_REMOVE))
		{
			if (message.message == WM_QUIT)
			{
				ProgramRunning = 0;
			}

			TranslateMessage(&message);
			DispatchMessage(&message);
		}

		BlitPattern();
	}

	return 0;
}
#endif